### ISSUE TITLE
Te dejo algunos comentarios del desafío de la tercera parte

### ISSUE THREAD

**Issue by ldevoto** [EmiNu5/LeaCurso#1]
Genial Eme, muy piola!!! 🚀🎸😅
Te dejo 5 comentarios. Revisalos de a uno y decime que te parecen.

---

1. Acá declaraste una variable `limite` que se usa exactamente igual y en los mismos lugares que `ocupada`. Podrías eliminar una de las dos sin problemas y renombrar la otra a `casillaIncorrecta` por ejemplo (o algo por el estilo) para que refleje la utilización que le estás dando:
https://github.com/EmiNu5/LeaCurso/blob/1679e89839db39c02c391149df50270d89e5b121/Ejercicios/Tercera%20parte/Cuarta%20tanda/tateti.go#L14-L15

---

2. Siguiendo, cuando imprimis el tablero la primera vez veo que lo limpiás (`tablero[x][y] = "" `):
https://github.com/EmiNu5/LeaCurso/blob/1679e89839db39c02c391149df50270d89e5b121/Ejercicios/Tercera%20parte/Cuarta%20tanda/tateti.go#L30-L43
Podrías limpiarlo antes haciendo lo que hacés cuando se reinicia el juego y despues mostrar el tablero exactamente igual pero sin el `tablero[x][y] = "" `: 
https://github.com/EmiNu5/LeaCurso/blob/1679e89839db39c02c391149df50270d89e5b121/Ejercicios/Tercera%20parte/Cuarta%20tanda/tateti.go#L166

---

3. Acá, cuando preguntás si hay un ganador o si es un empate:
https://github.com/EmiNu5/LeaCurso/blob/1679e89839db39c02c391149df50270d89e5b121/Ejercicios/Tercera%20parte/Cuarta%20tanda/tateti.go#L133-L163
Ejecutás el mismo código solo imprimís cosas distintas dependiendo de quien sea el ganador. Podrías sacar todo lo que se repite fuera del `if` y dejar dentro solo la impresion del ganador o empate. Por ejemplo así:
```go
	if ganador {
		fmt.Print("Has ganado ")
		if i%2 != 0 {
			fmt.Print(player1)
		} else {
			fmt.Print(player2)
		}
	} else if i == 8 {
		fmt.Print("Es un empate")
	}
	for {
		fmt.Println("\n Quieres volver a jugar? s/n")
		fmt.Scan(&repetir)
		if repetir == "s" || repetir == "n" {
			break
		}
	}
```
Si bien no son exactamente equivalentes ambas formas, la que te propongo es igualmente correcta solo que un poco más legible

---

4. En ese mismo pedazo de código: 
https://github.com/EmiNu5/LeaCurso/blob/1679e89839db39c02c391149df50270d89e5b121/Ejercicios/Tercera%20parte/Cuarta%20tanda/tateti.go#L137-L143
Hacés el for infinito y breakeas cuando el valor de `repetir` es `s` o `n`. Lo mismo se puede escribir de esta forma:
```go
	for repetir = ""; repetir != "s" && repetir != "n"; {
		fmt.Println("\n Quieres volver a jugar? s/n")
		fmt.Scan(&repetir)
	}
```
No está mal lo que hiciste, solo te muestro otra manera 😄 

---

5. Acá realmente importa si querés repetir porque hubo un ganador o porque se empato?
https://github.com/EmiNu5/LeaCurso/blob/1679e89839db39c02c391149df50270d89e5b121/Ejercicios/Tercera%20parte/Cuarta%20tanda/tateti.go#L164-L175
Me parece que lo que realmente importa es si se quiere repetir o no. Siendo así, se puede refactorizar un poco el código y escribirlo de la siguiente forma:
```go
	if repetir == "s" {
		tablero = [3][3]string{}
		gameover = false
		ganador = false
		repetir = ""
		i = 0
		break //<-- buscaría la forma de hacerlo sin un break
	} else {
		fmt.Println("Hasta la proxima")
		gameover = true
	}
```

**Comment by EmiNu5** [comment]
geniooooooo
